spring:
  config:
    import: "" # prod-ban ne töltsön be .env fájlokat a repóból
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

cors:
  allowed-origins:
    - https://app.mediweb.app
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

logging:
  level:
    root: info
    org.springframework.web: warn
    org.hibernate: error
