import { StyleSheet, Platform } from 'react-native';

// ════════════════════════════════════════════════════════
//  ADMIN STYLES — shared by AdminScreen shell and every tab
// ════════════════════════════════════════════════════════

export function createStyles(theme) {
    const isWeb = Platform.OS === 'web';
    return StyleSheet.create({
        container: { flex: 1, backgroundColor: theme.colors.background },
        // ── Tab Bar ──
        tabBar: {
            flexDirection: 'row',
            backgroundColor: theme.colors.backgroundCard,
            borderBottomWidth: 1,
            borderBottomColor: theme.colors.border,
            paddingHorizontal: 4,
            ...Platform.select({
                web: { position: 'sticky', top: 0, zIndex: 10 },
                default: {},
            }),
        },
        tab: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            paddingVertical: 14,
            gap: 6,
            borderBottomWidth: 2,
            borderBottomColor: 'transparent',
        },
        tabActive: { borderBottomColor: theme.colors.primary },
        tabLabel: { fontSize: 13, fontWeight: '600', color: theme.colors.textTertiary },
        tabLabelActive: { color: theme.colors.primary },
        // ── Content ──
        content: { flex: 1 },
        // NOTE: maxWidth/alignSelf/width used to center+cap page content here;
        // that responsibility now belongs to <ResponsiveContainer>, so only the
        // original padding values remain (see issue #76).
        contentInner: {
            padding: isWeb ? 24 : 14,
            paddingBottom: isWeb ? 48 : 120, // Extra bottom padding on mobile for tab bar
        },
        sectionTitle: { fontSize: 22, fontWeight: '700', color: theme.colors.textPrimary, marginBottom: 16 },
        subsectionTitle: { fontSize: 17, fontWeight: '600', color: theme.colors.textPrimary, marginTop: 24, marginBottom: 12 },
        // ── Dashboard Cards ──
        cardsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
        statCard: {
            backgroundColor: theme.colors.backgroundCard,
            borderRadius: theme.borderRadius.md,
            padding: 20,
            minWidth: isWeb ? 170 : '46%',
            flex: isWeb ? undefined : 1,
            borderWidth: 1,
            borderColor: theme.colors.border,
            ...theme.shadows.sm,
        },
        statIconWrap: { width: 40, height: 40, borderRadius: 10, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
        statValue: { fontSize: 28, fontWeight: '800', color: theme.colors.textPrimary },
        statLabel: { fontSize: 13, color: theme.colors.textSecondary, marginTop: 4 },
        // ── Search ──
        searchRow: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: theme.colors.backgroundCard,
            borderRadius: theme.borderRadius.md,
            borderWidth: 1,
            borderColor: theme.colors.border,
            paddingHorizontal: 14,
            marginBottom: 16,
        },
        searchInput: {
            flex: 1,
            paddingVertical: 12,
            fontSize: 14,
            color: theme.colors.textPrimary,
            ...Platform.select({ web: { outlineStyle: 'none' }, default: {} }),
        },
        // ── User Card ──
        userCard: {
            backgroundColor: theme.colors.backgroundCard,
            borderRadius: theme.borderRadius.md,
            padding: 16,
            marginBottom: 10,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        userHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
        userName: { fontSize: 15, fontWeight: '600', color: theme.colors.textPrimary },
        userEmail: { fontSize: 13, color: theme.colors.textSecondary, marginTop: 1 },
        roleBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, backgroundColor: theme.colors.primaryLight },
        roleBadgeAdmin: { backgroundColor: theme.colors.warning + '22' },
        roleBadgeText: { fontSize: 11, fontWeight: '700', color: theme.colors.primary },
        roleBadgeTextAdmin: { color: theme.colors.warning },
        userMeta: {
            flexDirection: isWeb ? 'row' : 'column',
            flexWrap: 'wrap',
            gap: isWeb ? 12 : 6,
            marginBottom: 12,
        },
        metaItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
        metaText: { fontSize: 12, color: theme.colors.textTertiary },
        userActions: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: 8,
            borderTopWidth: 1,
            borderTopColor: theme.colors.divider,
            paddingTop: 10,
        },
        actionBtn: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 5,
            paddingVertical: 6,
            paddingHorizontal: 10,
            borderRadius: 8,
            backgroundColor: theme.colors.backgroundElevated,
        },
        actionBtnText: { fontSize: 12, fontWeight: '600' },
        // ── Pagination ──
        pagination: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 16, marginTop: 16 },
        pageBtn: {
            width: 36,
            height: 36,
            borderRadius: 18,
            backgroundColor: theme.colors.backgroundCard,
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        pageBtnDisabled: { opacity: 0.4 },
        pageText: { fontSize: 14, fontWeight: '600', color: theme.colors.textSecondary },
        // ── Reviews ──
        filterRow: { flexDirection: 'row', gap: 8, marginBottom: 16 },
        filterBtn: {
            paddingHorizontal: 16,
            paddingVertical: 8,
            borderRadius: 20,
            backgroundColor: theme.colors.backgroundCard,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        filterBtnActive: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary },
        filterBtnText: { fontSize: 13, fontWeight: '600', color: theme.colors.textSecondary },
        filterBtnTextActive: { color: '#fff' },
        reportedHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: 14,
            backgroundColor: theme.colors.error + '10',
            borderRadius: theme.borderRadius.md,
            borderWidth: 1,
            borderColor: theme.colors.error + '30',
            marginBottom: 4,
        },
        reportedHeaderActive: { backgroundColor: theme.colors.error, borderColor: theme.colors.error },
        reportedHeaderText: { fontSize: 14, fontWeight: '600', color: theme.colors.error },
        reportedSection: {
            marginBottom: 16,
            borderLeftWidth: 2,
            borderLeftColor: theme.colors.error + '40',
            paddingLeft: 12,
            marginLeft: 4,
            marginTop: 8,
        },
        reportCard: {
            backgroundColor: theme.colors.backgroundCard,
            borderRadius: theme.borderRadius.md,
            padding: 16,
            marginBottom: 10,
            borderWidth: 1,
            borderColor: theme.colors.error + '25',
            borderLeftWidth: 3,
            borderLeftColor: theme.colors.error,
        },
        reportReasonRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 8 },
        reportReasonBadge: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 5,
            paddingHorizontal: 10,
            paddingVertical: 4,
            borderRadius: 12,
            backgroundColor: theme.colors.error + '15',
        },
        reportReasonText: { fontSize: 11, fontWeight: '700', color: theme.colors.error },
        reporterInfo: { fontSize: 12, color: theme.colors.textTertiary, marginBottom: 4 },
        reportComment: {
            fontSize: 13,
            color: theme.colors.textSecondary,
            fontStyle: 'italic',
            marginBottom: 8,
            paddingLeft: 8,
            borderLeftWidth: 2,
            borderLeftColor: theme.colors.border,
        },
        reportedReviewContent: {
            backgroundColor: theme.colors.backgroundElevated,
            borderRadius: theme.borderRadius.sm,
            padding: 12,
            marginBottom: 8,
            marginTop: 4,
        },
        reviewCard: {
            backgroundColor: theme.colors.backgroundCard,
            borderRadius: theme.borderRadius.md,
            padding: 16,
            marginBottom: 10,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        reviewHeader: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10 },
        reviewMedName: { fontSize: 15, fontWeight: '600', color: theme.colors.textPrimary },
        reviewAuthor: { fontSize: 12, color: theme.colors.textTertiary },
        reviewTextRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginBottom: 6 },
        reviewText: { flex: 1, fontSize: 13, color: theme.colors.textSecondary, lineHeight: 18 },
        reviewActions: {
            flexDirection: 'row',
            gap: 8,
            borderTopWidth: 1,
            borderTopColor: theme.colors.divider,
            paddingTop: 10,
            marginTop: 4,
        },
        emptyState: { alignItems: 'center', paddingVertical: 48, gap: 12 },
        emptyText: { fontSize: 15, color: theme.colors.textSecondary },
        // ── Sync ──
        syncStatusCard: {
            backgroundColor: theme.colors.backgroundCard,
            borderRadius: theme.borderRadius.md,
            padding: 20,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        syncStatusHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
        syncStatusDot: { width: 10, height: 10, borderRadius: 5 },
        syncStatusLabel: { fontSize: 15, fontWeight: '600', color: theme.colors.textPrimary },
        progressBarBg: {
            height: 8,
            borderRadius: 4,
            backgroundColor: theme.colors.border,
            marginBottom: 8,
            overflow: 'hidden',
        },
        progressBarFill: { height: '100%', borderRadius: 4 },
        syncProgressText: { fontSize: 13, color: theme.colors.textSecondary, marginBottom: 4 },
        syncMessage: { fontSize: 12, color: theme.colors.textTertiary, fontStyle: 'italic', marginTop: 4 },
        syncStatsRow: {
            flexDirection: 'row',
            justifyContent: 'space-around',
            marginTop: 16,
            paddingTop: 12,
            borderTopWidth: 1,
            borderTopColor: theme.colors.divider,
        },
        syncActionsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
        syncBtn: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            paddingVertical: 12,
            paddingHorizontal: 18,
            borderRadius: theme.borderRadius.md,
            flex: isWeb ? undefined : 1,
            minWidth: isWeb ? undefined : '45%',
        },
        syncBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
        // ── Config ──
        configCard: {
            backgroundColor: theme.colors.backgroundCard,
            borderRadius: theme.borderRadius.md,
            padding: 20,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        configRow: {
            flexDirection: isWeb ? 'row' : 'column',
            alignItems: isWeb ? 'center' : 'flex-start',
            marginBottom: 14,
            gap: isWeb ? 12 : 4,
        },
        configLabel: {
            fontSize: 13,
            fontWeight: '500',
            color: theme.colors.textSecondary,
            minWidth: isWeb ? 220 : undefined,
        },
        configInput: {
            backgroundColor: theme.colors.backgroundElevated,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: theme.colors.border,
            paddingHorizontal: 12,
            paddingVertical: 8,
            fontSize: 14,
            color: theme.colors.textPrimary,
            minWidth: isWeb ? 100 : undefined,
            width: isWeb ? undefined : '100%',
            ...Platform.select({ web: { outlineStyle: 'none' }, default: {} }),
        },
        saveConfigBtn: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            backgroundColor: theme.colors.primary,
            borderRadius: theme.borderRadius.md,
            paddingVertical: 12,
            marginTop: 8,
        },
        saveConfigBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
    });
}
