import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  reviewSection: {
    marginTop: 32,
    padding: 28,
    backgroundColor: "#fefefe",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    boxShadow: "0px 1px 4px rgba(0,0,0,0.05)",
  },
  reviewTitle: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 24,
    color: "#333",
    textAlign: "center",
  },
  ratingContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 32,
    marginBottom: 30,
  },
  ratingSummary: {
    width: "40%",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  ratingNumber: {
    fontSize: 56,
    fontWeight: "bold",
    color: "#fbc02d",
    marginBottom: 2,
  },
  totalRatingsText: {
    fontSize: 14,
    color: "#666",
    marginTop: 4,
  },
  distributionBox: {
    width: "55%",
    justifyContent: "center",
  },
  distributionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  starLabel: {
    width: 28,
    fontWeight: "600",
    textAlign: "left",
  },
  barBackground: {
    height: 10,
    backgroundColor: "#ddd",
    flex: 1,
    borderRadius: 5,
    marginHorizontal: 8,
  },
  barFill: {
    height: 10,
    backgroundColor: "#fbc02d",
    borderRadius: 5,
  },
  countLabel: {
    width: 24,
    textAlign: "right",
    fontSize: 13,
    color: "#444",
  },
  starRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginVertical: 6,
  },
  reviewForm: {
    marginBottom: 24,
  },
  reviewFormLabel: {
    fontWeight: "600",
    marginBottom: 6,
    marginTop: 12,
  },
  starPicker: {
    flexDirection: "row",
    marginBottom: 10,
  },
  reviewTextarea: {
    width: "100%",
    padding: 14,
    fontSize: 16,
    borderRadius: 8,
    borderColor: "#ccc",
    borderWidth: 1,
    backgroundColor: "#fff",
    marginBottom: 14,
  },
  reviewButton: {
    backgroundColor: "#66BB6A",
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 12,
    boxShadow: "0px 1px 3px rgba(0,0,0,0.1)",
    elevation: 2,
  },
  reviewButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  disabledButton: {
    backgroundColor: "#a5d6a7",
  },
  reviewCard: {
    backgroundColor: "#fafafa",
    borderWidth: 1,
    borderColor: "#ddd",
    padding: 14,
    borderRadius: 8,
    marginBottom: 16,
    boxShadow: "0px 1px 2px rgba(0,0,0,0.05)",
  },
  reviewText: {
    fontSize: 15,
    color: "#333",
    marginBottom: 4,
  },
  reviewMeta: {
    fontSize: 12,
    color: "#888",
    marginBottom: 6,
  },
  reviewListSection: {
    borderTopWidth: 1,
    borderTopColor: "#eee",
    paddingTop: 24,
    marginTop: 24,
  },
  reviewListTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#333",
    marginBottom: 12,
  },
  filterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 16,
  },
  dropdownWrapper: {
    backgroundColor: "#f1f1f1",
    borderRadius: 6,
    paddingHorizontal: 6,
  },
  dropdown: {
    padding: 6,
    fontSize: 14,
    borderRadius: 6,
    borderColor: "#ccc",
    borderWidth: 1,
    backgroundColor: "#fff",
  },
  noReviewsBox: {
    alignItems: "center",
    padding: 24,
    backgroundColor: "#f9f9f9",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ddd",
    marginTop: 12,
  },
  noReviewsTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#555",
    marginBottom: 6,
  },
  noReviewsSubtitle: {
    fontSize: 14,
    color: "#777",
    textAlign: "center",
    maxWidth: 300,
  },
  loginNotice: {
    backgroundColor: "#fff9c4",
    color: "#795548",
    borderWidth: 1,
    borderColor: "#fbc02d",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    textAlign: "center",
    fontWeight: "600",
    fontSize: 15,
    marginTop: 20,
    marginBottom: 16,
  },
  loginPrompt: {
    marginTop: 10,
    color: "#555",
    fontSize: 14,
    textAlign: "center",
  },
  loginLink: {
    color: "#2e7d32",
    fontWeight: "700",
    textDecorationLine: "underline",
    marginLeft: 4,
  },
});