import { StyleSheet } from "react-native";

export const createStyles = (theme, isMobile = false) => StyleSheet.create({
  pageWrapper: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  page: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  pageContent: {
    paddingHorizontal: isMobile ? 12 : 32,
    paddingBottom: isMobile ? 16 : 64,
    width: '100%',
    maxWidth: 1000,
    alignSelf: 'center',
    backgroundColor: theme.colors.background,
  },
  contentWrapper: {
    padding: isMobile ? 12 : 24,
    paddingTop: isMobile ? 8 : 24,
    paddingBottom: isMobile ? 12 : 24,
  },
  heroCard: {
    backgroundColor: theme.colors.primaryLight,
    borderRadius: isMobile ? 24 : 32,
    padding: isMobile ? 24 : 40,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    marginBottom: isMobile ? 20 : 32,
    borderWidth: 1,
    borderColor: theme.colors.primaryLight,
    ...theme.shadows.md,
  },
  heroText: {
    width: '100%',
  },
  heroTitle: {
    fontSize: isMobile ? 28 : 36,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.primaryDark,
    marginBottom: 12,
  },
  heroSubtitle: {
    fontSize: isMobile ? 15 : 18,
    lineHeight: isMobile ? 22 : 28,
    color: theme.colors.primaryDark,
    opacity: 0.8,
  },
  heroButton: {
    backgroundColor: theme.colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 26,
    borderRadius: 16,
    marginTop: 20,
    ...theme.shadows.sm,
  },
  heroButtonText: {
    color: theme.colors.white,
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.bold,
  },
  summaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: isMobile ? 20 : 32,
    marginHorizontal: isMobile ? -6 : -8,
  },
  summaryCard: {
    backgroundColor: theme.colors.backgroundCard,
    borderRadius: 20,
    padding: isMobile ? 16 : 20,
    flexGrow: 1,
    flexBasis: isMobile ? '45%' : '22%',
    minWidth: isMobile ? '45%' : 150,
    overflow: 'hidden',
    ...theme.shadows.sm,
    marginHorizontal: isMobile ? 6 : 8,
    marginBottom: isMobile ? 12 : 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  summaryIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: theme.colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  cardLabel: {
    fontSize: theme.fontSize.xs,
    color: theme.colors.textSecondary,
    fontWeight: theme.fontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  cardValue: {
    fontSize: 22,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textPrimary,
    marginTop: 4,
  },
  gridRow: {
    flexDirection: isMobile ? 'column' : 'row',
    justifyContent: isMobile ? 'flex-start' : 'space-between',
    marginTop: isMobile ? 0 : 8,
  },
  leftColumn: {
    width: isMobile ? '100%' : 'auto',
    flex: isMobile ? undefined : 1.6,
    marginRight: isMobile ? 0 : 16,
    marginBottom: isMobile ? 12 : 0,
  },
  rightColumn: {
    width: isMobile ? '100%' : 'auto',
    flex: isMobile ? undefined : 1,
    marginBottom: isMobile ? 12 : 0,
  },
  sectionCard: {
    backgroundColor: theme.colors.backgroundCard,
    borderRadius: 20,
    padding: isMobile ? 14 : 24,
    overflow: 'hidden',
    ...theme.shadows.md,
    marginBottom: isMobile ? 12 : 24,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: theme.fontSize.xl,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
    flex: 1,
  },
  sectionAction: {
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.primary,
    flexShrink: 0,
  },
  popularCard: {
    width: isMobile ? 220 : 260,
    marginRight: 16,
    padding: isMobile ? 16 : 18,
    backgroundColor: theme.colors.backgroundElevated,
    borderRadius: 18,
    overflow: 'hidden',
  },
  popularCardTitle: {
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
    marginBottom: 4,
  },
  popularCardMeta: {
    fontSize: theme.fontSize.xs,
    color: theme.colors.textTertiary,
    marginBottom: 8,
  },
  popularCardDescription: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },
  quickActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: isMobile ? 0 : -8,
  },
  quickActionCard: {
    backgroundColor: theme.colors.backgroundCard,
    borderRadius: 16,
    padding: isMobile ? 12 : 20,
    flexGrow: 1,
    flexBasis: isMobile ? '100%' : '48%',
    marginHorizontal: isMobile ? 0 : 8,
    marginBottom: isMobile ? 8 : 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    ...theme.shadows.sm,
  },
  quickActionIconWrapper: {
    width: isMobile ? 40 : 48,
    height: isMobile ? 40 : 48,
    borderRadius: 12,
    backgroundColor: theme.colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: isMobile ? 12 : 16,
  },
  quickActionContent: {
    flex: 1,
  },
  quickActionLabel: {
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textPrimary,
    marginBottom: 2,
  },
  quickActionDescription: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    lineHeight: 18,
  },
  reminderCard: {
    backgroundColor: theme.colors.backgroundElevated,
    padding: 20,
    borderRadius: 18,
  },
  reminderTitle: {
    fontSize: theme.fontSize.lg,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
    marginBottom: 6,
  },
  reminderInfo: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textSecondary,
  },
  todayCard: {
    backgroundColor: theme.colors.backgroundElevated,
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
  },
  todayCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  todayCardTitle: {
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
    flex: 1,
  },
  todayCardProfile: {
    fontSize: 13,
    color: theme.colors.textTertiary,
    flexShrink: 0,
    marginLeft: 8,
  },
  timeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -5,
  },
  timeChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 14,
    marginHorizontal: 5,
    marginBottom: 8,
  },
  timeChipPending: {
    backgroundColor: theme.colors.backgroundCard,
  },
  timeChipTaken: {
    backgroundColor: theme.colors.secondaryLight,
  },
  timeChipText: {
    fontSize: 13,
    color: theme.colors.textSecondary,
  },
  timeChipTextTaken: {
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
  },
  emptyState: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textTertiary,
  },
  errorBanner: {
    backgroundColor: theme.colors.error,
    borderRadius: 14,
    padding: 14,
    marginBottom: 20,
  },
  errorBannerText: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.white,
  },
  syncBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primaryLight,
    borderRadius: 20,
    padding: 20,
    marginBottom: 24,
    ...theme.shadows.sm,
  },
  syncSpinner: {
    marginRight: 16,
  },
  syncTextWrapper: {
    flex: 1,
  },
  syncTitle: {
    fontSize: theme.fontSize.lg,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
    marginBottom: 6,
  },
  syncSubtitle: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textSecondary,
    marginBottom: 4,
  },
  syncMeta: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    marginBottom: 2,
  },
  syncMetaSecondary: {
    fontSize: theme.fontSize.xs,
    color: theme.colors.textTertiary,
  },
  syncBannerIdle: {
    backgroundColor: theme.colors.backgroundCard,
    borderRadius: isMobile ? 16 : 20,
    padding: isMobile ? 14 : 18,
    marginBottom: isMobile ? 14 : 24,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  syncIdleTitle: {
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
    marginBottom: 6,
  },
  syncIdleSubtitle: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textSecondary,
    marginBottom: 4,
  },
  syncMetaWarning: {
    fontSize: 13,
    color: theme.colors.error,
    marginBottom: 4,
  },
  loadingState: {
    paddingVertical: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  guestContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 48,
  },
  authCard: {
    width: '100%',
    maxWidth: 520,
    backgroundColor: theme.colors.backgroundCard,
    borderRadius: 22,
    padding: 32,
    ...theme.shadows.lg,
  },
  title: {
    fontSize: 30,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textPrimary,
    marginBottom: 12,
  },
  subtitle: {
    fontSize: theme.fontSize.base,
    color: theme.colors.textSecondary,
    lineHeight: 22,
  },
  buttonRow: {
    marginTop: 28,
  },
  primaryButton: {
    backgroundColor: theme.colors.primary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 14,
  },
  primaryButtonText: {
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.white,
  },
  secondaryButton: {
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.primary,
  },
  secondaryButtonText: {
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.primary,
  },
  fullWidthButton: {
    width: '100%',
  },
  debugControls: {
    marginBottom: isMobile ? 14 : 24,
    alignItems: 'flex-start',
    width: '100%',
    backgroundColor: theme.colors.backgroundElevated,
    padding: isMobile ? 12 : 16,
    borderRadius: isMobile ? 14 : 16,
  },
  debugButton: {
    backgroundColor: theme.colors.primary,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  debugButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    flexWrap: 'wrap',
  },
  debugButtonStart: {
    marginRight: 12,
    marginBottom: 8,
  },
  debugButtonTest: {
    backgroundColor: theme.colors.primaryDark,
    marginRight: 12,
    marginBottom: 8,
  },
  debugButtonStop: {
    backgroundColor: theme.colors.error,
    marginBottom: 8,
  },
  debugButtonDisabled: {
    opacity: 0.6,
  },
  debugButtonText: {
    color: theme.colors.white,
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.semibold,
  },
  debugError: {
    color: theme.colors.error,
    fontSize: 13,
    marginBottom: 6,
  },
  debugInfo: {
    color: theme.colors.textSecondary,
    fontSize: 13,
    marginBottom: 10,
  },
  debugInfoSecondary: {
    color: theme.colors.textSecondary,
    fontSize: theme.fontSize.xs,
    marginBottom: 6,
  },
  debugInfoWarning: {
    color: theme.colors.error,
    fontSize: theme.fontSize.xs,
    marginBottom: 10,
  },
});
