import { StyleSheet } from "react-native";
import { theme } from 'styles/theme';

export const styles = StyleSheet.create({
  pageWrapper: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  page: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  pageContent: {
    paddingHorizontal: 32,
    paddingBottom: 64,
    width: '100%',
    maxWidth: 1000,
    alignSelf: 'center',
    backgroundColor: theme.colors.background,
  },
  contentWrapper: {
    width: '100%',
    paddingTop: 60, // Safe area for mobile (status bar + extra space)
    paddingBottom: 32,
    backgroundColor: theme.colors.background,
  },
  heroCard: {
    backgroundColor: theme.colors.white,
    borderRadius: 24,
    padding: 32,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    marginBottom: 28,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  heroText: {
    width: '100%',
  },
  heroTitle: {
    fontSize: 30,
    fontWeight: '700',
    color: theme.colors.textDark,
    marginBottom: 10,
  },
  heroSubtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: '#4F6956',
  },
  heroButton: {
    backgroundColor: theme.colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 26,
    borderRadius: 14,
  },
  heroButtonText: {
    color: theme.colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  summaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 32,
    marginHorizontal: -8,
  },
  summaryCard: {
    backgroundColor: theme.colors.white,
    borderRadius: 20,
    padding: 20,
    flexGrow: 1,
    flexBasis: 0,
    minWidth: 200,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
    marginHorizontal: 8,
    marginBottom: 16,
  },
  cardLabel: {
    fontSize: 14,
    color: '#637A68',
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  cardValue: {
    fontSize: 26,
    fontWeight: '700',
    color: theme.colors.textDark,
  },
  gridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  leftColumn: {
    flex: 1.6,
    marginRight: 16,
  },
  rightColumn: {
    flex: 1,
  },
  sectionCard: {
    backgroundColor: theme.colors.white,
    borderRadius: 22,
    padding: 24,
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: theme.colors.textDark,
  },
  sectionAction: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  popularCard: {
    width: 260,
    marginRight: 16,
    padding: 18,
    backgroundColor: '#f6faf7',
    borderRadius: 18,
  },
  popularCardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.textDark,
    marginBottom: 4,
  },
  popularCardMeta: {
    fontSize: 12,
    color: '#7C9284',
    marginBottom: 8,
  },
  popularCardDescription: {
    fontSize: 14,
    color: '#4F6956',
    lineHeight: 20,
  },
  quickActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -8,
  },
  quickActionCard: {
    backgroundColor: '#f6faf7',
    borderRadius: 18,
    padding: 18,
    flexGrow: 1,
    flexBasis: '48%',
    marginHorizontal: 8,
    marginBottom: 16,
  },
  quickActionLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.textDark,
    marginBottom: 8,
  },
  quickActionDescription: {
    fontSize: 13,
    color: '#4F6956',
    lineHeight: 18,
  },
  reminderCard: {
    backgroundColor: '#f6faf7',
    padding: 20,
    borderRadius: 18,
  },
  reminderTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.colors.textDark,
    marginBottom: 6,
  },
  reminderInfo: {
    fontSize: 14,
    color: '#4F6956',
  },
  todayCard: {
    backgroundColor: '#f6faf7',
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
  },
  todayCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  todayCardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.textDark,
  },
  todayCardProfile: {
    fontSize: 13,
    color: '#6f8574',
  },
  timeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -5,
  },
  timeChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 14,
    marginHorizontal: 5,
    marginBottom: 8,
  },
  timeChipPending: {
    backgroundColor: theme.colors.white,
  },
  timeChipTaken: {
    backgroundColor: '#dff3e7',
  },
  timeChipText: {
    fontSize: 13,
    color: '#4F6956',
  },
  timeChipTextTaken: {
    fontWeight: '600',
    color: theme.colors.textDark,
  },
  emptyState: {
    fontSize: 14,
    color: '#7C9284',
  },
  errorBanner: {
    backgroundColor: theme.colors.danger,
    borderRadius: 14,
    padding: 14,
    marginBottom: 20,
  },
  errorBannerText: {
    fontSize: 14,
    color: theme.colors.textDark,
  },
  syncBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e6f5eb',
    borderRadius: 20,
    padding: 20,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  syncSpinner: {
    marginRight: 16,
  },
  syncTextWrapper: {
    flex: 1,
  },
  syncTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.colors.textDark,
    marginBottom: 6,
  },
  syncSubtitle: {
    fontSize: 14,
    color: '#4F6956',
    marginBottom: 4,
  },
  syncMeta: {
    fontSize: 13,
    color: '#4F6956',
    marginBottom: 2,
  },
  syncMetaSecondary: {
    fontSize: 12,
    color: '#6f8574',
  },
  syncBannerIdle: {
    backgroundColor: theme.colors.white,
    borderRadius: 20,
    padding: 18,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#dbe7de',
  },
  syncIdleTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.textDark,
    marginBottom: 6,
  },
  syncIdleSubtitle: {
    fontSize: 14,
    color: '#4F6956',
    marginBottom: 4,
  },
  syncMetaWarning: {
    fontSize: 13,
    color: theme.colors.danger,
    marginBottom: 4,
  },
  loadingState: {
    paddingVertical: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  guestContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 48,
  },
  authCard: {
    width: '100%',
    maxWidth: 520,
    backgroundColor: theme.colors.white,
    borderRadius: 22,
    padding: 32,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  title: {
    fontSize: 30,
    fontWeight: '700',
    color: theme.colors.textDark,
    marginBottom: 12,
  },
  subtitle: {
    fontSize: 16,
    color: '#4F6956',
    lineHeight: 22,
  },
  buttonRow: {
    marginTop: 28,
  },
  primaryButton: {
    backgroundColor: theme.colors.primary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 14,
  },
  primaryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.white,
  },
  secondaryButton: {
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.primary,
  },
  secondaryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  fullWidthButton: {
    width: '100%',
  },
  debugControls: {
    marginBottom: 24,
    alignItems: 'flex-start',
    width: '100%',
    backgroundColor: '#f6faf7',
    padding: 16,
    borderRadius: 16,
  },
  debugButton: {
    backgroundColor: theme.colors.primary,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  debugButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    flexWrap: 'wrap',
  },
  debugButtonStart: {
    marginRight: 12,
    marginBottom: 8,
  },
  debugButtonTest: {
    backgroundColor: '#4F6956',
    marginRight: 12,
    marginBottom: 8,
  },
  debugButtonStop: {
    backgroundColor: theme.colors.danger,
    marginBottom: 8,
  },
  debugButtonDisabled: {
    opacity: 0.6,
  },
  debugButtonText: {
    color: theme.colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  debugError: {
    color: theme.colors.danger,
    fontSize: 13,
    marginBottom: 6,
  },
  debugInfo: {
    color: '#4F6956',
    fontSize: 13,
    marginBottom: 10,
  },
  debugInfoSecondary: {
    color: '#4F6956',
    fontSize: 12,
    marginBottom: 6,
  },
  debugInfoWarning: {
    color: theme.colors.danger,
    fontSize: 12,
    marginBottom: 10,
  },
});