import { StyleSheet } from "react-native";

export const createStyles = (theme) => StyleSheet.create({
  pageWrapper: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  page: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  pageContent: {
    paddingHorizontal: 32,
    paddingBottom: 64,
    width: '100%',
    maxWidth: 1000,
    alignSelf: 'center',
    backgroundColor: theme.colors.background,
  },
  contentWrapper: {
    width: '100%',
    paddingTop: 60,
    paddingBottom: 32,
    backgroundColor: theme.colors.background,
  },
  heroCard: {
    backgroundColor: theme.colors.backgroundCard,
    borderRadius: 24,
    padding: 32,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    marginBottom: 28,
    ...theme.shadows.lg,
  },
  heroText: {
    width: '100%',
  },
  heroTitle: {
    fontSize: 30,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textPrimary,
    marginBottom: 10,
  },
  heroSubtitle: {
    fontSize: theme.fontSize.base,
    lineHeight: 24,
    color: theme.colors.textSecondary,
  },
  heroButton: {
    backgroundColor: theme.colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 26,
    borderRadius: 14,
  },
  heroButtonText: {
    color: theme.colors.white,
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.semibold,
  },
  summaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 32,
    marginHorizontal: -8,
  },
  summaryCard: {
    backgroundColor: theme.colors.backgroundCard,
    borderRadius: 20,
    padding: 20,
    flexGrow: 1,
    flexBasis: 0,
    minWidth: 200,
    ...theme.shadows.md,
    marginHorizontal: 8,
    marginBottom: 16,
  },
  cardLabel: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textSecondary,
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  cardValue: {
    fontSize: 26,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textPrimary,
  },
  gridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  leftColumn: {
    flex: 1.6,
    marginRight: 16,
  },
  rightColumn: {
    flex: 1,
  },
  sectionCard: {
    backgroundColor: theme.colors.backgroundCard,
    borderRadius: 22,
    padding: 24,
    ...theme.shadows.md,
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: theme.fontSize.xl,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
  },
  sectionAction: {
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.primary,
  },
  popularCard: {
    width: 260,
    marginRight: 16,
    padding: 18,
    backgroundColor: theme.colors.backgroundElevated,
    borderRadius: 18,
  },
  popularCardTitle: {
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
    marginBottom: 4,
  },
  popularCardMeta: {
    fontSize: theme.fontSize.xs,
    color: theme.colors.textTertiary,
    marginBottom: 8,
  },
  popularCardDescription: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },
  quickActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -8,
  },
  quickActionCard: {
    backgroundColor: theme.colors.backgroundElevated,
    borderRadius: 18,
    padding: 18,
    flexGrow: 1,
    flexBasis: '48%',
    marginHorizontal: 8,
    marginBottom: 16,
  },
  quickActionLabel: {
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
    marginBottom: 8,
  },
  quickActionDescription: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    lineHeight: 18,
  },
  reminderCard: {
    backgroundColor: theme.colors.backgroundElevated,
    padding: 20,
    borderRadius: 18,
  },
  reminderTitle: {
    fontSize: theme.fontSize.lg,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
    marginBottom: 6,
  },
  reminderInfo: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textSecondary,
  },
  todayCard: {
    backgroundColor: theme.colors.backgroundElevated,
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
  },
  todayCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  todayCardTitle: {
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
  },
  todayCardProfile: {
    fontSize: 13,
    color: theme.colors.textTertiary,
  },
  timeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -5,
  },
  timeChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 14,
    marginHorizontal: 5,
    marginBottom: 8,
  },
  timeChipPending: {
    backgroundColor: theme.colors.backgroundCard,
  },
  timeChipTaken: {
    backgroundColor: theme.colors.secondaryLight,
  },
  timeChipText: {
    fontSize: 13,
    color: theme.colors.textSecondary,
  },
  timeChipTextTaken: {
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
  },
  emptyState: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textTertiary,
  },
  errorBanner: {
    backgroundColor: theme.colors.error,
    borderRadius: 14,
    padding: 14,
    marginBottom: 20,
  },
  errorBannerText: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.white,
  },
  syncBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primaryLight,
    borderRadius: 20,
    padding: 20,
    marginBottom: 24,
    ...theme.shadows.sm,
  },
  syncSpinner: {
    marginRight: 16,
  },
  syncTextWrapper: {
    flex: 1,
  },
  syncTitle: {
    fontSize: theme.fontSize.lg,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
    marginBottom: 6,
  },
  syncSubtitle: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textSecondary,
    marginBottom: 4,
  },
  syncMeta: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    marginBottom: 2,
  },
  syncMetaSecondary: {
    fontSize: theme.fontSize.xs,
    color: theme.colors.textTertiary,
  },
  syncBannerIdle: {
    backgroundColor: theme.colors.backgroundCard,
    borderRadius: 20,
    padding: 18,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  syncIdleTitle: {
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
    marginBottom: 6,
  },
  syncIdleSubtitle: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textSecondary,
    marginBottom: 4,
  },
  syncMetaWarning: {
    fontSize: 13,
    color: theme.colors.error,
    marginBottom: 4,
  },
  loadingState: {
    paddingVertical: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  guestContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 48,
  },
  authCard: {
    width: '100%',
    maxWidth: 520,
    backgroundColor: theme.colors.backgroundCard,
    borderRadius: 22,
    padding: 32,
    ...theme.shadows.lg,
  },
  title: {
    fontSize: 30,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textPrimary,
    marginBottom: 12,
  },
  subtitle: {
    fontSize: theme.fontSize.base,
    color: theme.colors.textSecondary,
    lineHeight: 22,
  },
  buttonRow: {
    marginTop: 28,
  },
  primaryButton: {
    backgroundColor: theme.colors.primary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 14,
  },
  primaryButtonText: {
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.white,
  },
  secondaryButton: {
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.primary,
  },
  secondaryButtonText: {
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.primary,
  },
  fullWidthButton: {
    width: '100%',
  },
  debugControls: {
    marginBottom: 24,
    alignItems: 'flex-start',
    width: '100%',
    backgroundColor: theme.colors.backgroundElevated,
    padding: 16,
    borderRadius: 16,
  },
  debugButton: {
    backgroundColor: theme.colors.primary,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  debugButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    flexWrap: 'wrap',
  },
  debugButtonStart: {
    marginRight: 12,
    marginBottom: 8,
  },
  debugButtonTest: {
    backgroundColor: theme.colors.primaryDark,
    marginRight: 12,
    marginBottom: 8,
  },
  debugButtonStop: {
    backgroundColor: theme.colors.error,
    marginBottom: 8,
  },
  debugButtonDisabled: {
    opacity: 0.6,
  },
  debugButtonText: {
    color: theme.colors.white,
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.semibold,
  },
  debugError: {
    color: theme.colors.error,
    fontSize: 13,
    marginBottom: 6,
  },
  debugInfo: {
    color: theme.colors.textSecondary,
    fontSize: 13,
    marginBottom: 10,
  },
  debugInfoSecondary: {
    color: theme.colors.textSecondary,
    fontSize: theme.fontSize.xs,
    marginBottom: 6,
  },
  debugInfoWarning: {
    color: theme.colors.error,
    fontSize: theme.fontSize.xs,
    marginBottom: 10,
  },
});
