import { StyleSheet } from "react-native";
import { theme } from "styles/theme";

export const styles = StyleSheet.create({
  reviewSection: {
    marginTop: 32,
    padding: 28,
    backgroundColor: theme.colors.backgroundCard,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    ...theme.shadows.sm,
  },
  reviewTitle: {
    fontSize: theme.fontSize.xxl,
    fontWeight: theme.fontWeight.bold,
    marginBottom: 24,
    color: theme.colors.textPrimary,
    textAlign: "center",
  },
  ratingContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 32,
    marginBottom: 30,
  },
  ratingSummary: {
    width: "40%",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  ratingNumber: {
    fontSize: 56,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.warning,
    marginBottom: 2,
  },
  totalRatingsText: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textSecondary,
    marginTop: 4,
  },
  distributionBox: {
    width: "55%",
    justifyContent: "center",
  },
  distributionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  starLabel: {
    width: 28,
    fontWeight: theme.fontWeight.semibold,
    textAlign: "left",
  },
  barBackground: {
    height: 10,
    backgroundColor: theme.colors.border,
    flex: 1,
    borderRadius: 5,
    marginHorizontal: 8,
  },
  barFill: {
    height: 10,
    backgroundColor: theme.colors.warning,
    borderRadius: 5,
  },
  countLabel: {
    width: 24,
    textAlign: "right",
    fontSize: 13,
    color: theme.colors.textSecondary,
  },
  starRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginVertical: 6,
  },
  reviewForm: {
    marginBottom: 24,
  },
  reviewFormLabel: {
    fontWeight: theme.fontWeight.semibold,
    marginBottom: 6,
    marginTop: 12,
  },
  starPicker: {
    flexDirection: "row",
    marginBottom: 10,
  },
  reviewTextarea: {
    width: "100%",
    padding: 14,
    fontSize: theme.fontSize.base,
    borderRadius: theme.borderRadius.sm,
    borderColor: theme.colors.borderDark,
    borderWidth: 1,
    backgroundColor: theme.colors.backgroundCard,
    marginBottom: 14,
  },
  reviewButton: {
    backgroundColor: theme.colors.primary,
    paddingVertical: 16,
    borderRadius: theme.borderRadius.sm,
    alignItems: "center",
    marginTop: 12,
    ...theme.shadows.sm,
  },
  reviewButtonText: {
    color: theme.colors.white,
    fontWeight: theme.fontWeight.bold,
    fontSize: theme.fontSize.base,
  },
  disabledButton: {
    backgroundColor: theme.colors.secondaryLight,
  },
  reviewCard: {
    backgroundColor: theme.colors.backgroundElevated,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: 14,
    borderRadius: theme.borderRadius.sm,
    marginBottom: 16,
    ...theme.shadows.sm,
  },
  reviewText: {
    fontSize: 15,
    color: theme.colors.textPrimary,
    marginBottom: 4,
  },
  reviewMeta: {
    fontSize: theme.fontSize.xs,
    color: theme.colors.textTertiary,
    marginBottom: 6,
  },
  reviewListSection: {
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
    paddingTop: 24,
    marginTop: 24,
  },
  reviewListTitle: {
    fontSize: theme.fontSize.xl,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textPrimary,
    marginBottom: 12,
  },
  filterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 16,
  },
  dropdownWrapper: {
    minWidth: 200,
  },
  noReviewsBox: {
    alignItems: "center",
    padding: theme.spacing.lg,
    backgroundColor: theme.colors.backgroundElevated,
    borderRadius: theme.borderRadius.sm,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginTop: 12,
  },
  noReviewsTitle: {
    fontSize: theme.fontSize.lg,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textSecondary,
    marginBottom: 6,
  },
  noReviewsSubtitle: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textTertiary,
    textAlign: "center",
    maxWidth: 300,
  },
  loginNotice: {
    backgroundColor: "#FEF9C3",
    color: theme.colors.textSecondary,
    borderWidth: 1,
    borderColor: theme.colors.warning,
    borderRadius: theme.borderRadius.sm,
    paddingVertical: 12,
    paddingHorizontal: 16,
    textAlign: "center",
    fontWeight: theme.fontWeight.semibold,
    fontSize: 15,
    marginTop: 20,
    marginBottom: 16,
  },
  loginPrompt: {
    marginTop: 10,
    color: theme.colors.textSecondary,
    fontSize: theme.fontSize.sm,
    textAlign: "center",
  },
  loginLink: {
    color: theme.colors.primary,
    fontWeight: theme.fontWeight.bold,
    textDecorationLine: "underline",
    marginLeft: 4,
  },
});
