import { StyleSheet } from "react-native";
import { theme } from "styles/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 32,
    backgroundColor: theme.colors.white,
    width: "100%",
  },
  title: {
    fontSize: 32,
    fontWeight: "bold",
    marginBottom: 24,
    color: "#000",
  },
  searchRow: {
    flexDirection: "row",
    width: "100%",
    gap: 12,
    marginBottom: 16,
  },
  searchInput: {
    flex: 1,
    backgroundColor: "#f1f1f1",
    padding: 10,
    marginBottom: 12,
    borderRadius: 8,
    fontSize: 16,
  },
  searchButton: {
    backgroundColor: "#66BB6A",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    borderRadius: 8,
    marginBottom: 12,
  },
  searchButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
  },
  checkboxRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    marginBottom: 16,
    width: "100%",
  },
  checkbox: {
    fontSize: 16,
    backgroundColor: "#f1f1f1",
    padding: 10,
    borderRadius: 8,
  },
  expandFilters: {
    fontSize: 16,
    fontWeight: "bold",
    marginVertical: 12,
  },
  filtersContainer: {
    width: "100%",
    backgroundColor: "#fafafa",
    borderRadius: 8,
    padding: 16,
    marginBottom: 24,
  },
  filterGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    width: "100%",
    justifyContent: "space-between",
  },
  filterInput: {
    width: "22%",
    minWidth: 150,
    backgroundColor: "#f1f1f1",
    padding: 10,
    marginBottom: 12,
    borderRadius: 6,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#ddd",
    height: 46,
    boxSizing: "border-box",
  },
  select: {
    width: "22%",
    minWidth: 150,
    backgroundColor: "#f1f1f1",
    padding: 10,
    marginBottom: 12,
    borderRadius: 6,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#ddd",
    height: 46,
    boxSizing: "border-box",
  },
  dateInput: {
    width: "22%",
    minWidth: 150,
    backgroundColor: "#f1f1f1",
    padding: 10,
    marginBottom: 12,
    borderRadius: 8,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#ddd",
    height: 46,
    boxSizing: "border-box",
  },
  loadingWrapper: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 40,
  },
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 16,
  },
  viewSwitcher: {
    flexDirection: "row",
    gap: 12,
  },
  resultCount: {
    fontSize: 16,
    fontWeight: "600",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    columnGap: '2%',
    justifyContent: "flex-start",
  },
  gridItem: {
    width: "32%",
    minWidth: 200,
    backgroundColor: "#fafafa",
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ddd",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  listItem: {
    width: "100%",
    maxWidth: 1200,
    backgroundColor: "#fafafa",
    padding: 16,
    marginBottom: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ddd",
    alignSelf: "stretch",
  },  
  medName: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 8,
  },
  substance: {
    fontSize: 14,
    color: "#555",
  },
  company: {
    fontSize: 13,
    color: "#888",
    marginTop: 2,
  },
  status: {
    fontSize: 12,
    color: "#aaa",
    marginTop: 2,
  },
  loadMoreButton: {
    marginTop: 20,
    padding: 10,
    backgroundColor: "#ddd",
    borderRadius: 5,
    alignSelf: "center",
  },
  loadMoreText: {
    fontSize: 16,
    color: "#333",
  }
});