import { StyleSheet } from "react-native";
import { theme } from "styles/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
    width: "100%",
    alignItems: "center",
  },
  contentWrapper: {
    width: "100%",
    maxWidth: 1000,
    paddingHorizontal: 16, // Reduced from 32px for better mobile use
    paddingTop: 60, // Safe area for mobile (status bar + extra space)
    paddingVertical: 32,
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    marginBottom: 16,
    color: "#1F2937",
  },
  subtitle: {
    fontSize: 16,
    color: "#64748B",
    marginBottom: 24,
  },
  // Modern Search Bar
  searchBarContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 56,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  searchIcon: {
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#1F2937",
    height: "100%",
  },
  clearButton: {
    padding: 8,
    marginLeft: 8,
  },
  // Quick Filters
  quickFiltersContainer: {
    marginBottom: 20,
  },
  quickFiltersHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  quickFiltersTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1F2937",
  },
  clearFiltersText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#2E7D32",
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    minHeight: 48, // Accessibility: minimum touch target
  },
  filterChipActive: {
    backgroundColor: "#2E7D32",
    borderColor: "#2E7D32",
  },
  chipIcon: {
    marginRight: 6,
  },
  filterChipText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#475569",
  },
  filterChipTextActive: {
    color: "#FFFFFF",
    fontWeight: "600",
  },
  filterSectionTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#2E7D32",
    marginTop: 16,
    marginBottom: 10,
  },
  expandFilters: {
    fontSize: 16,
    fontWeight: "600",
    marginVertical: 12,
    color: "#2E7D32",
    textAlign: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "#F8FAFC",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  filtersContainer: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  filterGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    width: "100%",
    justifyContent: "flex-start",
  },
  filterInput: {
    width: "48%",
    minWidth: 200,
    backgroundColor: "#F8FAFC",
    padding: 16,
    borderRadius: 10,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    height: 56,
  },
  select: {
    width: "22%",
    minWidth: 150,
    backgroundColor: "#FFFFFF",
    padding: 12,
    marginBottom: 12,
    borderRadius: 10,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    height: 46,
    boxSizing: "border-box",
  },
  dateInput: {
    width: "48%",
    minWidth: 200,
    backgroundColor: "#F8FAFC",
    padding: 16,
    borderRadius: 10,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    height: 56,
  },
  loadingWrapper: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 60,
  },
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  viewSwitcher: {
    flexDirection: "row",
    gap: 8,
    backgroundColor: "#FFFFFF",
    padding: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  viewSwitcherButton: {
    padding: 8,
    borderRadius: 6,
  },
  viewSwitcherButtonActive: {
    backgroundColor: "#E8F5E9",
  },
  resultCount: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    columnGap: '2%',
    justifyContent: "flex-start",
  },
  gridItem: {
    width: "32%",
    minWidth: 200,
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "flex-start",
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  listItem: {
    width: "100%",
    maxWidth: 1200,
    backgroundColor: "#FFFFFF",
    padding: 16,
    marginBottom: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignSelf: "stretch",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  medName: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 8,
    color: "#1F2937",
  },
  substance: {
    fontSize: 15,
    color: "#475569",
    marginBottom: 4,
  },
  company: {
    fontSize: 14,
    color: "#64748B",
    marginTop: 4,
  },
  status: {
    fontSize: 13,
    color: "#64748B",
    marginTop: 6,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
  },
  inactiveStatus: {
    color: "#c62828",
    fontWeight: "600",
  },
  loadMoreButton: {
    marginTop: 24,
    paddingVertical: 14,
    paddingHorizontal: 32,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    alignSelf: "center",
    borderWidth: 2,
    borderColor: "#66BB6A",
  },
  loadMoreText: {
    fontSize: 16,
    color: "#2E7D32",
    fontWeight: "600",
  },
  emptyState: {
    marginTop: 40,
    fontSize: 16,
    color: "#64748B",
    textAlign: "center",
    width: "100%",
    padding: 32,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  }
});  ,
  // Skeleton Loading
  skeletonContainer: {
    width: "100%",
    marginTop: 20,
  },
  skeletonCard: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  skeletonLine: {
    height: 16,
    backgroundColor: "#F1F5F9",
    borderRadius: 4,
    marginBottom: 12,
  },
  skeletonLineShort: {
    width: "60%",
  },
  // Empty State
  emptyStateContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 80,
    paddingHorizontal: 32,
  },
  emptyStateTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#1F2937",
    marginTop: 24,
    marginBottom: 8,
  },
  emptyStateSubtitle: {
    fontSize: 16,
    color: "#64748B",
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 24,
  },
  clearAllButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F0FDF4",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#BBF7D0",
  },
  clearAllButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2E7D32",
  }
});
