import { StyleSheet } from "react-native";

export const createStyles = (theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  contentWrapper: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: theme.spacing.md,
  },
  card: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: theme.colors.backgroundCard,
    padding: 20,
    borderRadius: theme.borderRadius.sm,
    alignItems: "center",
    ...theme.shadows.md,
  },
  title: {
    fontSize: 28,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.primary,
    marginBottom: 20,
    textAlign: "center",
  },
  input: {
    width: "100%",
    backgroundColor: theme.colors.backgroundInput || theme.colors.backgroundCard,
    padding: theme.components?.input?.padding || 12,
    borderRadius: theme.components?.input?.borderRadius || 8,
    fontSize: theme.fontSize.base,
    marginBottom: theme.spacing.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    color: theme.colors.textPrimary,
  },
  passwordContainer: {
    width: "100%",
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.backgroundInput || theme.colors.backgroundCard,
    borderRadius: theme.components?.input?.borderRadius || 8,
    marginBottom: theme.spacing.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  passwordInput: {
    flex: 1,
    padding: theme.components?.input?.padding || 12,
    fontSize: theme.fontSize.base,
    color: theme.colors.textPrimary,
  },
  eyeIcon: {
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    backgroundColor: theme.colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: theme.borderRadius.sm,
    width: "100%",
    alignItems: "center",
    marginBottom: 12,
  },
  buttonText: {
    color: theme.colors.white,
    fontSize: theme.fontSize.lg,
    fontWeight: theme.fontWeight.bold,
  },
  linkText: {
    color: theme.colors.primary,
    marginTop: 16,
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.bold,
    textAlign: "center",
    textDecorationLine: "underline",
  },
  googleButton: {
    flexDirection: 'row',
    backgroundColor: theme.colors.white,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: theme.borderRadius.sm,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#DADCE0',
    marginTop: 10,
  },
  googleButtonText: {
    color: '#3C4043',
    fontSize: theme.fontSize.lg,
    fontWeight: theme.fontWeight.bold,
    marginLeft: 10,
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginVertical: 15,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: theme.colors.border,
  },
  dividerText: {
    color: theme.colors.textTertiary,
    paddingHorizontal: 10,
    fontSize: theme.fontSize.sm,
  },
  guestLink: {
    marginTop: 20,
    paddingVertical: 8,
    alignItems: 'center',
  },
  guestLinkText: {
    color: theme.colors.textTertiary,
    fontSize: theme.fontSize.sm,
    textDecorationLine: 'underline',
  },
});
